blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Request or Idea
    url: https://github.com/btuckerc/dictation/discussions
    about: Please post feature requests and ideas in Dictation Discussions
  - name: 💬 General Discussion
    url: https://github.com/btuckerc/dictation/discussions
    about: Ask questions and discuss Dictation with the community
